// <auto-generated />
using System;
using Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20251224014917_VotoEmprendimiento1")]
    partial class VotoEmprendimiento1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmprendimientoFoto", b =>
                {
                    b.Property<int>("EmprendimientosId")
                        .HasColumnType("int");

                    b.Property<int>("FotosId")
                        .HasColumnType("int");

                    b.HasKey("EmprendimientosId", "FotosId");

                    b.HasIndex("FotosId");

                    b.ToTable("EmprendimientoFotos", (string)null);
                });

            modelBuilder.Entity("Modelo.AgendaPresentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmprendimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdEvento")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEmprendimiento");

                    b.HasIndex("IdEvento");

                    b.ToTable("AgendaPresentaciones");
                });

            modelBuilder.Entity("Modelo.CargoParticipante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CargosParticipante");
                });

            modelBuilder.Entity("Modelo.CategoriaPremio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasPremio");
                });

            modelBuilder.Entity("Modelo.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HoraCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmprendimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("IdEmprendimiento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Modelo.Cronograma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cronogramas");
                });

            modelBuilder.Entity("Modelo.Emprendimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("IdFacultad")
                        .HasColumnType("int");

                    b.Property<int>("IdRubroEmprendimiento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("IdFacultad");

                    b.HasIndex("IdRubroEmprendimiento");

                    b.ToTable("Emprendimientos");
                });

            modelBuilder.Entity("Modelo.EmprendimientoPremiacion", b =>
                {
                    b.Property<int>("IdEmprendimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdPremiacion")
                        .HasColumnType("int");

                    b.HasKey("IdEmprendimiento", "IdPremiacion");

                    b.HasIndex("IdPremiacion");

                    b.ToTable("EmprendimientoPremiacion");
                });

            modelBuilder.Entity("Modelo.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Modelo.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("Modelo.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("Modelo.Participante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdCargoParticipante")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmprendimiento")
                        .HasColumnType("int");

                    b.Property<int?>("IdFoto")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("IdCargoParticipante");

                    b.HasIndex("IdEmprendimiento");

                    b.HasIndex("IdFoto");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("NumeroTelefono")
                        .IsUnique();

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("Modelo.Premiacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinPremiacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioPremiacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FechaInicioPremiacion", "FechaFinPremiacion");

                    b.ToTable("Premiacion");
                });

            modelBuilder.Entity("Modelo.Presentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Expositor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Presentaciones");
                });

            modelBuilder.Entity("Modelo.Properties.MenuOpciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("IdRolUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("IdRolUsuario");

                    b.HasIndex("Code", "Grupo");

                    b.ToTable("MenuOpciones");
                });

            modelBuilder.Entity("Modelo.ResultadoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategoriaPremio")
                        .HasColumnType("int");

                    b.Property<int>("IdEmprendimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdPremiacion")
                        .HasColumnType("int");

                    b.Property<int>("Puesto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoriaPremio");

                    b.HasIndex("IdEmprendimiento");

                    b.HasIndex("IdPremiacion");

                    b.ToTable("ResultadoEventos");
                });

            modelBuilder.Entity("Modelo.RolUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("RolUsuarios");
                });

            modelBuilder.Entity("Modelo.RubroEmprendimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("RubrosEmprendimiento");
                });

            modelBuilder.Entity("Modelo.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("IdRolUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdRolUsuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Modelo.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEmprendimiento")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEmprendimiento")
                        .IsUnique();

                    b.HasIndex("IdUsuario");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("Modelo.VotoPremiacion", b =>
                {
                    b.Property<int>("IdVoto")
                        .HasColumnType("int");

                    b.Property<int>("IdPremiacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("IdVoto", "IdPremiacion");

                    b.HasIndex("IdPremiacion");

                    b.ToTable("VotoPremiacion");
                });

            modelBuilder.Entity("EmprendimientoFoto", b =>
                {
                    b.HasOne("Modelo.Emprendimiento", null)
                        .WithMany()
                        .HasForeignKey("EmprendimientosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Foto", null)
                        .WithMany()
                        .HasForeignKey("FotosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelo.AgendaPresentacion", b =>
                {
                    b.HasOne("Modelo.Emprendimiento", "Emprendimiento")
                        .WithMany()
                        .HasForeignKey("IdEmprendimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("IdEvento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Modelo.Comentario", b =>
                {
                    b.HasOne("Modelo.Emprendimiento", "Emprendimiento")
                        .WithMany()
                        .HasForeignKey("IdEmprendimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Modelo.Emprendimiento", b =>
                {
                    b.HasOne("Modelo.Facultad", "Facultad")
                        .WithMany()
                        .HasForeignKey("IdFacultad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.RubroEmprendimiento", "RubroEmprendimiento")
                        .WithMany()
                        .HasForeignKey("IdRubroEmprendimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facultad");

                    b.Navigation("RubroEmprendimiento");
                });

            modelBuilder.Entity("Modelo.EmprendimientoPremiacion", b =>
                {
                    b.HasOne("Modelo.Emprendimiento", "Emprendimiento")
                        .WithMany("Premicaciones")
                        .HasForeignKey("IdEmprendimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Premiacion", "Premiacion")
                        .WithMany("Emprendimientos")
                        .HasForeignKey("IdPremiacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");

                    b.Navigation("Premiacion");
                });

            modelBuilder.Entity("Modelo.Participante", b =>
                {
                    b.HasOne("Modelo.CargoParticipante", "CargoParticipante")
                        .WithMany()
                        .HasForeignKey("IdCargoParticipante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Emprendimiento", "Emprendimiento")
                        .WithMany("Participantes")
                        .HasForeignKey("IdEmprendimiento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Modelo.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("IdFoto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CargoParticipante");

                    b.Navigation("Emprendimiento");

                    b.Navigation("Foto");
                });

            modelBuilder.Entity("Modelo.Properties.MenuOpciones", b =>
                {
                    b.HasOne("Modelo.RolUsuario", "RolUsuario")
                        .WithMany()
                        .HasForeignKey("IdRolUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RolUsuario");
                });

            modelBuilder.Entity("Modelo.ResultadoEvento", b =>
                {
                    b.HasOne("Modelo.CategoriaPremio", "CategoriaPremio")
                        .WithMany()
                        .HasForeignKey("IdCategoriaPremio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Emprendimiento", "Emprendimiento")
                        .WithMany()
                        .HasForeignKey("IdEmprendimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modelo.Premiacion", "Premiacion")
                        .WithMany()
                        .HasForeignKey("IdPremiacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaPremio");

                    b.Navigation("Emprendimiento");

                    b.Navigation("Premiacion");
                });

            modelBuilder.Entity("Modelo.Usuario", b =>
                {
                    b.HasOne("Modelo.RolUsuario", "RolUsuario")
                        .WithMany()
                        .HasForeignKey("IdRolUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolUsuario");
                });

            modelBuilder.Entity("Modelo.Voto", b =>
                {
                    b.HasOne("Modelo.Emprendimiento", "Emprendimiento")
                        .WithOne()
                        .HasForeignKey("Modelo.Voto", "IdEmprendimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprendimiento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Modelo.VotoPremiacion", b =>
                {
                    b.HasOne("Modelo.Premiacion", "Premiacion")
                        .WithMany("Votos")
                        .HasForeignKey("IdPremiacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modelo.Voto", "Voto")
                        .WithMany("Premiaciones")
                        .HasForeignKey("IdVoto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premiacion");

                    b.Navigation("Voto");
                });

            modelBuilder.Entity("Modelo.Emprendimiento", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Premicaciones");
                });

            modelBuilder.Entity("Modelo.Premiacion", b =>
                {
                    b.Navigation("Emprendimientos");

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Modelo.Voto", b =>
                {
                    b.Navigation("Premiaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
